cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- '3.11'
python_abi_tag:
 - cp37m
 - cp38
 - cp39
 - cp310
 - cp311
 - cp312
python_impl:
- cpython
python_impl_version:
 - 3.7
 - 3.8
 - 3.9
 - 3.10
 - 3.11
 - 3.12
python_implementation:
 - cpython
 - cpython
 - cpython
 - cpython
 - cpython
 - cpython
python_version:
 - 3.7
 - 3.8
 - 3.9
 - 3.10
 - 3.11
 - 3.12
target_platform:
- linux-armv7l
zip_keys:
- - python
  - python_impl
- - python_abi_tag
  - python_version
  - python_impl_version
  - python_implementation
